all:
    children:
        manager:
            hosts:
                swarm-manager:

        worker:
            hosts:
                swarm-worker:
    
    vars: 
        ansible_user: Thomas
        ansible_ssh_private_key_file: "/home/Thomas/.ssh/id_rsa"